Repository GDG-on-Campus-KHU/AOS-assignments, pull requests merged in 2025-01, with the labels that each got.

#10 Week7_Assignment
  taehoon/Week7_Assignment/Week7_Assignment/.gitignore
  taehoon/Week7_Assignment/Week7_Assignment/.idea/.gitignore
  taehoon/Week7_Assignment/Week7_Assignment/.idea/compiler.xml
  taehoon/Week7_Assignment/Week7_Assignment/.idea/gradle.xml
  taehoon/Week7_Assignment/Week7_Assignment/.idea/misc.xml
  taehoon/Week7_Assignment/Week7_Assignment/app/.gitignore
  taehoon/Week7_Assignment/Week7_Assignment/app/build.gradle
  taehoon/Week7_Assignment/Week7_Assignment/app/proguard-rules.pro
  taehoon/Week7_Assignment/Week7_Assignment/app/src/androidTest/java/com/example/week7_assignment/ExampleInstrumentedTest.kt
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/AndroidManifest.xml
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/java/com/example/week7_assignment/MainActivity.kt
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/java/com/example/week7_assignment/ui/theme/Color.kt
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/java/com/example/week7_assignment/ui/theme/Shape.kt
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/java/com/example/week7_assignment/ui/theme/Theme.kt
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/java/com/example/week7_assignment/ui/theme/Type.kt
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/drawable/ic_launcher_background.xml
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/values/colors.xml
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/values/strings.xml
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/values/themes.xml
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/xml/backup_rules.xml
  taehoon/Week7_Assignment/Week7_Assignment/app/src/main/res/xml/data_extraction_rules.xml
  taehoon/Week7_Assignment/Week7_Assignment/app/src/test/java/com/example/week7_assignment/ExampleUnitTest.kt
  taehoon/Week7_Assignment/Week7_Assignment/build.gradle
  taehoon/Week7_Assignment/Week7_Assignment/gradle.properties
  taehoon/Week7_Assignment/Week7_Assignment/gradle/wrapper/gradle-wrapper.jar
  taehoon/Week7_Assignment/Week7_Assignment/gradle/wrapper/gradle-wrapper.properties
  taehoon/Week7_Assignment/Week7_Assignment/gradlew
  taehoon/Week7_Assignment/Week7_Assignment/gradlew.bat
  taehoon/Week7_Assignment/Week7_Assignment/settings.gradle
Labels: 과제 제출, 태훈

#12 7주차 데이터 상태 제출
  ahyeon/week07/.gitignore
  ahyeon/week07/.idea/.gitignore
  ahyeon/week07/.idea/.name
  ahyeon/week07/.idea/compiler.xml
  ahyeon/week07/.idea/gradle.xml
  ahyeon/week07/.idea/kotlinc.xml
  ahyeon/week07/.idea/misc.xml
  ahyeon/week07/.idea/vcs.xml
  ahyeon/week07/app/.gitignore
  ahyeon/week07/app/build.gradle.kts
  ahyeon/week07/app/proguard-rules.pro
  ahyeon/week07/app/src/androidTest/java/com/example/fetchstatus/ExampleInstrumentedTest.kt
  ahyeon/week07/app/src/main/AndroidManifest.xml
  ahyeon/week07/app/src/main/java/com/example/fetchstatus/MainActivity.kt
  ahyeon/week07/app/src/main/java/com/example/fetchstatus/ui/theme/Color.kt
  ahyeon/week07/app/src/main/java/com/example/fetchstatus/ui/theme/Theme.kt
  ahyeon/week07/app/src/main/java/com/example/fetchstatus/ui/theme/Type.kt
  ahyeon/week07/app/src/main/res/drawable/ic_launcher_background.xml
  ahyeon/week07/app/src/main/res/drawable/ic_launcher_foreground.xml
  ahyeon/week07/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  ahyeon/week07/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  ahyeon/week07/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  ahyeon/week07/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  ahyeon/week07/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  ahyeon/week07/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  ahyeon/week07/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  ahyeon/week07/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  ahyeon/week07/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  ahyeon/week07/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  ahyeon/week07/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  ahyeon/week07/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  ahyeon/week07/app/src/main/res/values/colors.xml
  ahyeon/week07/app/src/main/res/values/strings.xml
  ahyeon/week07/app/src/main/res/values/themes.xml
  ahyeon/week07/app/src/main/res/xml/backup_rules.xml
  ahyeon/week07/app/src/main/res/xml/data_extraction_rules.xml
  ahyeon/week07/app/src/test/java/com/example/fetchstatus/ExampleUnitTest.kt
  ahyeon/week07/build.gradle.kts
  ahyeon/week07/gradle.properties
  ahyeon/week07/gradle/wrapper/gradle-wrapper.jar
  ahyeon/week07/gradle/wrapper/gradle-wrapper.properties
  ahyeon/week07/gradlew
  ahyeon/week07/gradlew.bat
  ahyeon/week07/settings.gradle.kts
Labels: 아현, 과제 제출

#11 8주차 뉴스 카드 앱 제작
  ahyeon/week08/.gitignore
  ahyeon/week08/.idea/.gitignore
  ahyeon/week08/.idea/.name
  ahyeon/week08/.idea/compiler.xml
  ahyeon/week08/.idea/gradle.xml
  ahyeon/week08/.idea/kotlinc.xml
  ahyeon/week08/.idea/misc.xml
  ahyeon/week08/.idea/vcs.xml
  ahyeon/week08/app/.gitignore
  ahyeon/week08/app/build.gradle.kts
  ahyeon/week08/app/proguard-rules.pro
  ahyeon/week08/app/src/androidTest/java/com/example/week8/ExampleInstrumentedTest.kt
  ahyeon/week08/app/src/main/AndroidManifest.xml
  ahyeon/week08/app/src/main/java/com/example/week8/MainActivity.kt
  ahyeon/week08/app/src/main/java/com/example/week8/ui/theme/Color.kt
  ahyeon/week08/app/src/main/java/com/example/week8/ui/theme/Theme.kt
  ahyeon/week08/app/src/main/java/com/example/week8/ui/theme/Type.kt
  ahyeon/week08/app/src/main/res/drawable/ic_launcher_background.xml
  ahyeon/week08/app/src/main/res/drawable/ic_launcher_foreground.xml
  ahyeon/week08/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  ahyeon/week08/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  ahyeon/week08/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  ahyeon/week08/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  ahyeon/week08/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  ahyeon/week08/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  ahyeon/week08/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  ahyeon/week08/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  ahyeon/week08/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  ahyeon/week08/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  ahyeon/week08/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  ahyeon/week08/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  ahyeon/week08/app/src/main/res/values/colors.xml
  ahyeon/week08/app/src/main/res/values/strings.xml
  ahyeon/week08/app/src/main/res/values/themes.xml
  ahyeon/week08/app/src/main/res/xml/backup_rules.xml
  ahyeon/week08/app/src/main/res/xml/data_extraction_rules.xml
  ahyeon/week08/app/src/test/java/com/example/week8/ExampleUnitTest.kt
  ahyeon/week08/build.gradle.kts
  ahyeon/week08/gradle.properties
  ahyeon/week08/gradle/wrapper/gradle-wrapper.jar
  ahyeon/week08/gradle/wrapper/gradle-wrapper.properties
  ahyeon/week08/gradlew
  ahyeon/week08/gradlew.bat
  ahyeon/week08/settings.gradle.kts
Labels: 아현, 과제 제출

#16 Week8_assignment
  donghyeon/Week8_assignment/.gitignore
  donghyeon/Week8_assignment/.idea/.gitignore
  donghyeon/Week8_assignment/.idea/compiler.xml
  donghyeon/Week8_assignment/.idea/deploymentTargetSelector.xml
  donghyeon/Week8_assignment/.idea/deviceManager.xml
  donghyeon/Week8_assignment/.idea/gradle.xml
  donghyeon/Week8_assignment/.idea/inspectionProfiles/Project_Default.xml
  donghyeon/Week8_assignment/.idea/kotlinc.xml
  donghyeon/Week8_assignment/.idea/migrations.xml
  donghyeon/Week8_assignment/.idea/misc.xml
  donghyeon/Week8_assignment/.idea/runConfigurations.xml
  donghyeon/Week8_assignment/.idea/vcs.xml
  donghyeon/Week8_assignment/app/.gitignore
  donghyeon/Week8_assignment/app/build.gradle.kts
  donghyeon/Week8_assignment/app/proguard-rules.pro
  donghyeon/Week8_assignment/app/src/androidTest/java/com/example/week8_assignment/ExampleInstrumentedTest.kt
  donghyeon/Week8_assignment/app/src/main/AndroidManifest.xml
  donghyeon/Week8_assignment/app/src/main/java/com/example/week8_assignment/MainActivity.kt
  donghyeon/Week8_assignment/app/src/main/java/com/example/week8_assignment/Model.kt
  donghyeon/Week8_assignment/app/src/main/java/com/example/week8_assignment/RetrofitAPI.kt
  donghyeon/Week8_assignment/app/src/main/java/com/example/week8_assignment/ui/NewsAppScreen.kt
  donghyeon/Week8_assignment/app/src/main/java/com/example/week8_assignment/ui/theme/Color.kt
  donghyeon/Week8_assignment/app/src/main/java/com/example/week8_assignment/ui/theme/Theme.kt
  donghyeon/Week8_assignment/app/src/main/java/com/example/week8_assignment/ui/theme/Type.kt
  donghyeon/Week8_assignment/app/src/main/res/drawable/ic_launcher_background.xml
  donghyeon/Week8_assignment/app/src/main/res/drawable/ic_launcher_foreground.xml
  donghyeon/Week8_assignment/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  donghyeon/Week8_assignment/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  donghyeon/Week8_assignment/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  donghyeon/Week8_assignment/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  donghyeon/Week8_assignment/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  donghyeon/Week8_assignment/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  donghyeon/Week8_assignment/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  donghyeon/Week8_assignment/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  donghyeon/Week8_assignment/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  donghyeon/Week8_assignment/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  donghyeon/Week8_assignment/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  donghyeon/Week8_assignment/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  donghyeon/Week8_assignment/app/src/main/res/values/colors.xml
  donghyeon/Week8_assignment/app/src/main/res/values/strings.xml
  donghyeon/Week8_assignment/app/src/main/res/values/themes.xml
  donghyeon/Week8_assignment/app/src/main/res/xml/backup_rules.xml
  donghyeon/Week8_assignment/app/src/main/res/xml/data_extraction_rules.xml
  donghyeon/Week8_assignment/app/src/test/java/com/example/week8_assignment/ExampleUnitTest.kt
  donghyeon/Week8_assignment/build.gradle.kts
  donghyeon/Week8_assignment/gradle.properties
  donghyeon/Week8_assignment/gradle/libs.versions.toml
  donghyeon/Week8_assignment/gradle/wrapper/gradle-wrapper.jar
  donghyeon/Week8_assignment/gradle/wrapper/gradle-wrapper.properties
  donghyeon/Week8_assignment/gradlew
  donghyeon/Week8_assignment/gradlew.bat
  donghyeon/Week8_assignment/settings.gradle.kts
Labels: 동현, 과제 제출

#17 Week8_Assignment_1
  taehoon/Week8_Assignment/Week8_Assignment/.gitignore
  taehoon/Week8_Assignment/Week8_Assignment/.idea/.gitignore
  taehoon/Week8_Assignment/Week8_Assignment/.idea/compiler.xml
  taehoon/Week8_Assignment/Week8_Assignment/.idea/gradle.xml
  taehoon/Week8_Assignment/Week8_Assignment/.idea/inspectionProfiles/Project_Default.xml
  taehoon/Week8_Assignment/Week8_Assignment/.idea/misc.xml
  taehoon/Week8_Assignment/Week8_Assignment/app/.gitignore
  taehoon/Week8_Assignment/Week8_Assignment/app/build.gradle
  taehoon/Week8_Assignment/Week8_Assignment/app/proguard-rules.pro
  taehoon/Week8_Assignment/Week8_Assignment/app/src/androidTest/java/com/example/week8_assignment/ExampleInstrumentedTest.kt
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/AndroidManifest.xml
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/java/com/example/week8_assignment/MainActivity.kt
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/java/com/example/week8_assignment/ui/theme/Color.kt
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/java/com/example/week8_assignment/ui/theme/Shape.kt
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/java/com/example/week8_assignment/ui/theme/Theme.kt
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/java/com/example/week8_assignment/ui/theme/Type.kt
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/drawable/ic_launcher_background.xml
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/values/colors.xml
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/values/strings.xml
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/values/themes.xml
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/xml/backup_rules.xml
  taehoon/Week8_Assignment/Week8_Assignment/app/src/main/res/xml/data_extraction_rules.xml
  taehoon/Week8_Assignment/Week8_Assignment/app/src/test/java/com/example/week8_assignment/ExampleUnitTest.kt
  taehoon/Week8_Assignment/Week8_Assignment/build.gradle
  taehoon/Week8_Assignment/Week8_Assignment/gradle.properties
  taehoon/Week8_Assignment/Week8_Assignment/gradle/wrapper/gradle-wrapper.jar
  taehoon/Week8_Assignment/Week8_Assignment/gradle/wrapper/gradle-wrapper.properties
  taehoon/Week8_Assignment/Week8_Assignment/gradlew
  taehoon/Week8_Assignment/Week8_Assignment/gradlew.bat
  taehoon/Week8_Assignment/Week8_Assignment/settings.gradle
Labels: 과제 제출, 태훈

#18 9주차 과제 제출
  ahyeon/week09/.gitignore
  ahyeon/week09/.idea/.gitignore
  ahyeon/week09/.idea/.name
  ahyeon/week09/.idea/compiler.xml
  ahyeon/week09/.idea/gradle.xml
  ahyeon/week09/.idea/inspectionProfiles/Project_Default.xml
  ahyeon/week09/.idea/kotlinc.xml
  ahyeon/week09/.idea/misc.xml
  ahyeon/week09/.idea/vcs.xml
  ahyeon/week09/app/.gitignore
  ahyeon/week09/app/build.gradle.kts
  ahyeon/week09/app/proguard-rules.pro
  ahyeon/week09/app/src/androidTest/java/com/example/myapplication/ExampleInstrumentedTest.kt
  ahyeon/week09/app/src/main/AndroidManifest.xml
  ahyeon/week09/app/src/main/java/com/example/myapplication/MainActivity.kt
  ahyeon/week09/app/src/main/java/com/example/myapplication/ui/theme/Color.kt
  ahyeon/week09/app/src/main/java/com/example/myapplication/ui/theme/Theme.kt
  ahyeon/week09/app/src/main/java/com/example/myapplication/ui/theme/Type.kt
  ahyeon/week09/app/src/main/res/drawable/ic_launcher_background.xml
  ahyeon/week09/app/src/main/res/drawable/ic_launcher_foreground.xml
  ahyeon/week09/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  ahyeon/week09/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  ahyeon/week09/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  ahyeon/week09/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  ahyeon/week09/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  ahyeon/week09/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  ahyeon/week09/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  ahyeon/week09/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  ahyeon/week09/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  ahyeon/week09/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  ahyeon/week09/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  ahyeon/week09/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  ahyeon/week09/app/src/main/res/values/colors.xml
  ahyeon/week09/app/src/main/res/values/strings.xml
  ahyeon/week09/app/src/main/res/values/themes.xml
  ahyeon/week09/app/src/main/res/xml/backup_rules.xml
  ahyeon/week09/app/src/main/res/xml/data_extraction_rules.xml
  ahyeon/week09/app/src/test/java/com/example/myapplication/ExampleUnitTest.kt
  ahyeon/week09/build.gradle.kts
  ahyeon/week09/gradle.properties
  ahyeon/week09/gradle/wrapper/gradle-wrapper.jar
  ahyeon/week09/gradle/wrapper/gradle-wrapper.properties
  ahyeon/week09/gradlew
  ahyeon/week09/gradlew.bat
  ahyeon/week09/settings.gradle.kts
Labels: 아현, 과제 제출

#19 Week9_Assignment
  taehoon/Week9_Assignment/.gitignore
  taehoon/Week9_Assignment/.idea/.gitignore
  taehoon/Week9_Assignment/.idea/compiler.xml
  taehoon/Week9_Assignment/.idea/gradle.xml
  taehoon/Week9_Assignment/.idea/inspectionProfiles/Project_Default.xml
  taehoon/Week9_Assignment/.idea/misc.xml
  taehoon/Week9_Assignment/app/.gitignore
  taehoon/Week9_Assignment/app/build.gradle
  taehoon/Week9_Assignment/app/proguard-rules.pro
  taehoon/Week9_Assignment/app/src/androidTest/java/com/example/week9_assignment/ExampleInstrumentedTest.kt
  taehoon/Week9_Assignment/app/src/main/AndroidManifest.xml
  taehoon/Week9_Assignment/app/src/main/java/com/example/week9_assignment/MainActivity.kt
  taehoon/Week9_Assignment/app/src/main/java/com/example/week9_assignment/save.kt
  taehoon/Week9_Assignment/app/src/main/java/com/example/week9_assignment/ui/theme/Color.kt
  taehoon/Week9_Assignment/app/src/main/java/com/example/week9_assignment/ui/theme/Shape.kt
  taehoon/Week9_Assignment/app/src/main/java/com/example/week9_assignment/ui/theme/Theme.kt
  taehoon/Week9_Assignment/app/src/main/java/com/example/week9_assignment/ui/theme/Type.kt
  taehoon/Week9_Assignment/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  taehoon/Week9_Assignment/app/src/main/res/drawable/ic_launcher_background.xml
  taehoon/Week9_Assignment/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  taehoon/Week9_Assignment/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  taehoon/Week9_Assignment/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  taehoon/Week9_Assignment/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  taehoon/Week9_Assignment/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  taehoon/Week9_Assignment/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  taehoon/Week9_Assignment/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  taehoon/Week9_Assignment/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  taehoon/Week9_Assignment/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  taehoon/Week9_Assignment/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  taehoon/Week9_Assignment/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  taehoon/Week9_Assignment/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  taehoon/Week9_Assignment/app/src/main/res/values/colors.xml
  taehoon/Week9_Assignment/app/src/main/res/values/strings.xml
  taehoon/Week9_Assignment/app/src/main/res/values/themes.xml
  taehoon/Week9_Assignment/app/src/main/res/xml/backup_rules.xml
  taehoon/Week9_Assignment/app/src/main/res/xml/data_extraction_rules.xml
  taehoon/Week9_Assignment/app/src/test/java/com/example/week9_assignment/ExampleUnitTest.kt
  taehoon/Week9_Assignment/build.gradle
  taehoon/Week9_Assignment/gradle.properties
  taehoon/Week9_Assignment/gradle/wrapper/gradle-wrapper.jar
  taehoon/Week9_Assignment/gradle/wrapper/gradle-wrapper.properties
  taehoon/Week9_Assignment/gradlew
  taehoon/Week9_Assignment/gradlew.bat
  taehoon/Week9_Assignment/settings.gradle
Labels: 과제 제출, 태훈

#20 Week9_assignment
  donghyeon/Week5_assignment/.idea/other.xml
  donghyeon/Week6_assignment/.idea/other.xml
  donghyeon/Week9_assignment/.gitignore
  donghyeon/Week9_assignment/.idea/.gitignore
  donghyeon/Week9_assignment/.idea/compiler.xml
  donghyeon/Week9_assignment/.idea/deploymentTargetSelector.xml
  donghyeon/Week9_assignment/.idea/gradle.xml
  donghyeon/Week9_assignment/.idea/inspectionProfiles/Project_Default.xml
  donghyeon/Week9_assignment/.idea/kotlinc.xml
  donghyeon/Week9_assignment/.idea/migrations.xml
  donghyeon/Week9_assignment/.idea/misc.xml
  donghyeon/Week9_assignment/.idea/runConfigurations.xml
  donghyeon/Week9_assignment/.idea/vcs.xml
  donghyeon/Week9_assignment/app/.gitignore
  donghyeon/Week9_assignment/app/build.gradle.kts
  donghyeon/Week9_assignment/app/proguard-rules.pro
  donghyeon/Week9_assignment/app/src/androidTest/java/com/example/week9_assignment/ExampleInstrumentedTest.kt
  donghyeon/Week9_assignment/app/src/main/AndroidManifest.xml
  donghyeon/Week9_assignment/app/src/main/java/com/example/week9_assignment/DataStore.kt
  donghyeon/Week9_assignment/app/src/main/java/com/example/week9_assignment/MainActivity.kt
  donghyeon/Week9_assignment/app/src/main/java/com/example/week9_assignment/Room.kt
  donghyeon/Week9_assignment/app/src/main/java/com/example/week9_assignment/ViewModel.kt
  donghyeon/Week9_assignment/app/src/main/java/com/example/week9_assignment/ui/MainScreen.kt
  donghyeon/Week9_assignment/app/src/main/java/com/example/week9_assignment/ui/theme/Color.kt
  donghyeon/Week9_assignment/app/src/main/java/com/example/week9_assignment/ui/theme/Theme.kt
  donghyeon/Week9_assignment/app/src/main/java/com/example/week9_assignment/ui/theme/Type.kt
  donghyeon/Week9_assignment/app/src/main/res/drawable/ic_launcher_background.xml
  donghyeon/Week9_assignment/app/src/main/res/drawable/ic_launcher_foreground.xml
  donghyeon/Week9_assignment/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  donghyeon/Week9_assignment/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  donghyeon/Week9_assignment/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  donghyeon/Week9_assignment/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  donghyeon/Week9_assignment/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  donghyeon/Week9_assignment/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  donghyeon/Week9_assignment/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  donghyeon/Week9_assignment/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  donghyeon/Week9_assignment/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  donghyeon/Week9_assignment/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  donghyeon/Week9_assignment/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  donghyeon/Week9_assignment/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  donghyeon/Week9_assignment/app/src/main/res/values/colors.xml
  donghyeon/Week9_assignment/app/src/main/res/values/strings.xml
  donghyeon/Week9_assignment/app/src/main/res/values/themes.xml
  donghyeon/Week9_assignment/app/src/main/res/xml/backup_rules.xml
  donghyeon/Week9_assignment/app/src/main/res/xml/data_extraction_rules.xml
  donghyeon/Week9_assignment/app/src/test/java/com/example/week9_assignment/ExampleUnitTest.kt
  donghyeon/Week9_assignment/build.gradle.kts
  donghyeon/Week9_assignment/gradle.properties
  donghyeon/Week9_assignment/gradle/libs.versions.toml
  donghyeon/Week9_assignment/gradle/wrapper/gradle-wrapper.jar
  donghyeon/Week9_assignment/gradle/wrapper/gradle-wrapper.properties
  donghyeon/Week9_assignment/gradlew
  donghyeon/Week9_assignment/gradlew.bat
  donghyeon/Week9_assignment/settings.gradle.kts
Labels: 동현, 과제 제출
